export const PRODUCTS = {
  FETCH_PRODUCTS: 'products/FETCH_PRODUCTS',
  FETCH_PRODUCT_BY_ID: 'products/FETCH_PRODUCT_BY_ID',
  CREATE_PRODUCT: 'products/CREATE_PRODUCT',
  UPDATE_PRODUCT: 'products/UPDATE_PRODUCT',
  DELETE_PRODUCT: 'products/DELETE_PRODUCT',
};
